dgPadCmsUser/Models/Class.cs
namespace dgPadCmsUser.Models
{
    public class Class
    {
    }
}

dgPadCmsUser/Models/IndexViewModel.cs
using dgPadCms.Models;
using System.Collections.Generic;

namespace dgPadCmsUser.Models
{
    public class IndexViewModel
    {
        public List<Post> lastFivePosts { get; set; }
        public List<PostType> firstPostType { get; set; }
        public List<Post> secondPostType { get; set; }
        public List<Post> thirdPostType { get; set; }
        public List<Term> indexTerms { get; set; }
    }
}

dgPadCmsUser/Controllers/UserHomeController.cs
using dgPadCms.Infrastructure;
using dgPadCms.Models;
using dgPadCmsUser.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace dgPadCmsUser.Controllers
{
    public class UserHomeController : Controller
    {
        private readonly dgPadCmsContext context;

        public UserHomeController(dgPadCmsContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            IndexViewModel indexViewModel = new IndexViewModel();

            indexViewModel.lastFivePosts = await context.Posts.OrderByDescending(x => x.PostId).Where(x => x.PostTypeId != 6).Take(5).ToListAsync();

            var lastThreePostTypes = await context.PostTypes.OrderByDescending(x => x.PostTypeId).Take(3).ToListAsync();

            indexViewModel.indexTerms = await context.Terms.OrderByDescending(x => x.TermId).ToListAsync();


            //First PostType 
            ViewBag.NewestPostType = await context.PostTypes.FindAsync(lastThreePostTypes[0].PostTypeId);
            ViewBag.NewestPostTypePosts = await context.Posts.Where(x => x.PostTypeId == lastThreePostTypes[0].PostTypeId).Take(5).ToListAsync();

            ////Second PostType 
            ViewBag.SecondNewestPostType = await context.PostTypes.FindAsync(lastThreePostTypes[1].PostTypeId);
            ViewBag.SecondNewestPostTypePosts = await context.Posts.Where(x => x.PostTypeId == lastThreePostTypes[1].PostTypeId).Take(5).ToListAsync();

            ////Third PostType 
            ViewBag.ThirdNewestPostType = await context.PostTypes.FindAsync(lastThreePostTypes[2].PostTypeId);
            ViewBag.ThirdNewestPostTypePosts = await context.Posts.Where(x => x.PostTypeId == lastThreePostTypes[2].PostTypeId).Take(4).ToListAsync();

            //Taxonomies
            //ViewBag.Taxonomies = await context.Taxonomies.OrderByDescending(x => x.TaxonomyId).Take(6).ToListAsync();

            //Last 3 post for shared layout
            ViewBag.LastThreePostsSharedLayout = await context.Posts.OrderByDescending(x => x.PostId).Take(3).ToListAsync();
            return View(indexViewModel);
        }

        public async Task<IActionResult> TaxonomyIndex(int TaxonomyId)
        {
            ViewBag.taxonomy = await context.Taxonomies.FindAsync(TaxonomyId);
            var terms = await context.Terms.Where(x => x.TaxonomyId == TaxonomyId).ToListAsync();


            //var postType = await context.PostTypeTaxonomies.Where(x => x.TaxanomyId == TaxonomyId).ToListAsync();

            List<PostTerm> postTerms = new List<PostTerm>();

            foreach (var i in terms)
            {
                postTerms.AddRange(await context.PostTerms.Where(x => x.TermId == i.TermId).ToListAsync());
            };

            List<int> postsId = new List<int>();

            foreach (var i in postTerms)
            {
                postsId.Add(i.PostId);
            }

            var postsIdWithoutDup = postsId.Distinct().ToList();

            ViewBag.TaxonomyPosts = await context.Posts.Where(x => postsIdWithoutDup.Contains(x.PostId)).ToListAsync();

           
            return View();
        }

        public async Task<IActionResult> TermIndex(int TermId)
        {
            var term = await context.Terms.FindAsync(TermId);

            ViewBag.term = term;

            

            List< PostTerm> postTerms = new List<PostTerm>();

            
             postTerms = await context.PostTerms.Where(x => x.TermId == term.TermId).ToListAsync();


            List<int> postsId = new List<int>();

            foreach (var i in postTerms)
            {
                postsId.Add(i.PostId);
            }

            //var postsIdWithoutDup = postsId.Distinct().ToList();

            ViewBag.TermPosts = await context.Posts.Where(x => postsId.Contains(x.PostId)).ToListAsync();

           
            return View();
        }

        public async Task<IActionResult> SinglePost(int postId)
        {
            var post = await context.Posts.FindAsync(postId);

            ViewBag.terms = await context.Terms.OrderByDescending(x => x.TermId).ToListAsync();
            ViewBag.post = post;
            return View();
        }


        public IActionResult Contact()
        {
            return View();
        }
            public IActionResult Privacy()
        {
            return View();
        }

        
    }
}

dgPadCmsUser/Views/Shared/_Layout.cshtml
@model dgPadCmsUser.Models.IndexViewModel

<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/css/css/media_query.css" rel="stylesheet" type="text/css" />
    <link href="~/css/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="~/css/css/animate.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="~/css/css/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="~/css/css/owl.theme.default.css" rel="stylesheet" type="text/css" />
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/21/21601.png">
    <!-- Bootstrap CSS -->
    <link href="~/css/css/style_1.css" rel="stylesheet" type="text/css" />
    <!-- Modernizr JS -->
    <script src="~/js/modernizr-3.5.0.min.js"></script>
</head>
<body>
    
    <div class="container-fluid bg-faded fh5co_padd_mediya padding_786">
    <div class="container padding_786">
        <nav class="navbar navbar-toggleable-md navbar-light ">
            <button class="navbar-toggler navbar-toggler-right mt-3" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="fa fa-bars"></span></button>
                <a class="navbar-brand" href="#"><img src="https://cdn-icons-png.flaticon.com/512/21/21601.png" alt="img" class="mobile_logo_width" /></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                            <a class="navbar-brand" asp-controller="UserHome" asp-action="Index"><img src="https://cdn-icons-png.flaticon.com/512/21/21601.png" alt="img" width="60" height="60" /></a>
                    </li>
                    <li class="nav-item active">
                            <a class="nav-link" asp-controller="UserHome" asp-action="Index" >Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton3" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Taxonomies<span class="sr-only">(current)</span></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink_1">
                            @using dgPadCms.Infrastructure
                            @inject dgPadCmsContext context 
                                @{
                                    var taxonomiesList =  context.Taxonomies.OrderByDescending(x => x.TaxonomyId).Take(6).ToList();
                                    //var LastThreePostsSharedLayout = context.PostTypes.OrderByDescending(x => x.PostTypeId).Take(3).ToList();
                                    var LastThreePostsSharedLayout =  context.Posts.OrderByDescending(x => x.PostId).Take(3).ToList();

                            }

                                @foreach (var i in taxonomiesList)
                            {
                                    <a class="dropdown-item" asp-controller="UserHome" asp-action="TaxonomyIndex" asp-route-TaxonomyId="@i.TaxonomyId">@i.TaxonomyName</a>
                            }
                        </div>
                    </li>
                    <li class="nav-item ">
                            <a class="nav-link" asp-controller="UserHome" asp-action="Contact">Contact <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
    <main role="main">
        @RenderBody()
    </main>

    <div class="container-fluid fh5co_footer_bg py-5 ">
        <dxxiv class="container animate-box mt-5">
            <div class="row justify-content-md-center">
                <div class="clearfix"></div>
                <div class="col-12 col-md-4 col-lg-3">
                    <div class="footer_main_title py-3"> About</div>
                    <div class="footer_sub_about pb-3">
                        The Lebanon News is an Lebanese daily newspaper, founded and continuously published in Beirut since September 18,
                        1851. It has won 112 Pulitzer Prizes, more than any other news organization. Its website is one of Lebanon’s most popular news sites,
                        and the most popular among all the nation’s newspapers,
                        receiving more than 30 million unique visitors per month as reported in January 2011.
                    </div>
                </div>
                <div class="col-12 col-md-3 col-lg-2">
                    <div class="footer_main_title py-3"> Taxonomies</div>
                    <ul class="footer_menu">
                        @foreach (var i in taxonomiesList)
                        {
                            <li><a href="#" class=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp; @i.TaxonomyName</a></li>

                        }
                    </ul>
                </div>
                <div class="col-12 col-md-5 col-lg-3 position_footer_relative">
                    <div class="footer_main_title py-3"> Last Added Posts</div>
                    @foreach (var i in LastThreePostsSharedLayout)
                    {
                        <div class="footer_makes_sub_font"> @i.PostCreatoinDate</div>
                        <a href="#" class="footer_post pb-4"> @i.PostTitle </a>
                    }
                    <div class="footer_position_absolute"><img src="~/Media/images/footer_sub_tipik.png" alt="img" class="width_footer_sub_img" /></div>
                </div>
            </div>
        </dxxiv>
    </div>
    <div class="container-fluid fh5co_footer_right_reserved">
        <div class="container">
            <div class="row  ">
                <div class="col-12 col-md-6 py-4 Reserved"> © Copyright 2022, All rights reserved. Design by <a href="http://recursivesolutions.org/" title="Free HTML5 Bootstrap templates">recursivesolutions</a>. </div>
            </div>
        </div>

        <div class="gototop js-top">
            <a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <!--<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
                integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
                integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
                crossorigin="anonymous"></script>
        <!-- Waypoints -->
        <script src="~/js/jquery.waypoints.min.js"></script>
        <!-- Main -->
        <script src="~/js/main.js"></script>
    </div>
</body>
</html>

dgPadCmsUser/Views/UserHome/Index.cshtml
@model dgPadCmsUser.Models.IndexViewModel


@{
    ViewData["Title"] = "Home Page";
}
<div class="container-fluid paddding mb-5">
    <div class="row mx-0">
        <div class="col-md-6 col-12 paddding animate-box" data-animate-effect="fadeIn">
           <div class="fh5co_suceefh5co_height">
                <img src="/images/@Model.lastFivePosts[0].Image" alt="img" />
                <div class="fh5co_suceefh5co_height_position_absolute"></div>
                <div class="fh5co_suceefh5co_height_position_absolute_font">
                    <div class="">
                        <a href="#" class="color_fff">
                            <i class="fa fa-clock-o"></i>&nbsp;&nbsp;@Model.lastFivePosts[0].PostCreatoinDate
                        </a>
                    </div>
                    <div class=""><a class="fh5co_good_font" asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@Model.lastFivePosts[0].PostId"> @Model.lastFivePosts[0].PostTitle </a></div>
                </div>
           </div>
        </div>
            <div class="col-md-6">
                <div class="row">
                    @for( int item = 1; item < Model.lastFivePosts.Count(); item++ )
                    {
                    <div class="col-md-6 col-6 paddding animate-box" data-animate-effect="fadeIn">
                        <div class="fh5co_suceefh5co_height_2">
                        <img src="/images/@Model.lastFivePosts[item].Image" alt="img" />
                            <div class="fh5co_suceefh5co_height_position_absolute"></div>
                            <div class="fh5co_suceefh5co_height_position_absolute_font_2">
                                <div class="">
                                    <a href="#" class="color_fff">
                                    <i class="fa fa-clock-o"></i>&nbsp;&nbsp;@Model.lastFivePosts[item].PostCreatoinDate
                                    </a>
                                </div>
                                <div class=""><a class="fh5co_good_font_2" asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@Model.lastFivePosts[item].PostId">@Model.lastFivePosts[item].PostTitle</a></div>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
    </div>
    </div>
<div class="container-fluid pt-3">
    <div class="container animate-box" data-animate-effect="fadeIn">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">@ViewBag.NewestPostType.PostTypeTitle</div>
        </div>
        <div class="owl-carousel owl-theme js" id="slider1">
            @foreach (var i in ViewBag.NewestPostTypePosts)
            {
                <div class="item px-2">
                    <div class="fh5co_latest_trading_img_position_relative">
                    <div class="fh5co_latest_trading_img"><img src="/images/@i.Image" alt=""
                                                           class="fh5co_img_special_relative"/></div>
                    <div class="fh5co_latest_trading_img_position_absolute"></div>
                    <div class="fh5co_latest_trading_img_position_absolute_1">
                            <a asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@i.PostId" class="text-white"> @i.PostTitle </a>
                            <div class="fh5co_latest_trading_date_and_name_color"> @i.PostCreatoinDate</div>
                    </div>
                </div>
            </div>
        }
        </div>
    </div> 
</div>
<div class="container-fluid fh5co_video_news_bg pb-4">
    <div class="container animate-box" data-animate-effect="fadeIn">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom pt-5 pb-2 mb-4  text-black">@ViewBag.SecondNewestPostType.PostTypeTitle</div>
        </div>
       
            <div class="owl-carousel owl-theme" id="slider3">
            @foreach (var i in ViewBag.SecondNewestPostTypePosts)
            {
                <div class="item px-2">
                    <div class="fh5co_hover_news_img">
                        <div class="fh5co_hover_news_img_video_tag_position_relative">
                            <div class="fh5co_news_img">
                                <iframe width="100%" height="200" src="@i.VideoUrl" ></iframe>
                            </div>
                            <div class="fh5co_hover_news_img_video_tag_position_absolute_1 fh5co_hide" id="play-video">
                                <div class="fh5co_hover_news_img_video_tag_position_absolute_1_play_button_1">
                                    <div class="fh5co_hover_news_img_video_tag_position_absolute_1_play_button">
                                        <span><i class="fa fa-play"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pt-2">
                            <a asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@i.PostId" class="link-secondary">
                                    <span class="h5">@i.PostTitle </span>
                                </a>
                                <div class="c_g"><i class="fa fa-clock-o"></i>@i.PostCreatoinDate</div>
                        </div>
                    </div>
                </div>
               }
            </div>         
    </div>
</div>

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">@ViewBag.ThirdNewestPostType.PostTypeTitle</div>
                @foreach (var i in ViewBag.ThirdNewestPostTypePosts)
                {
            
                    <div class="row pb-4">
                        <div class="col-md-5">
                            <div class="fh5co_hover_news_img">
                                <div class="fh5co_news_img"><img src="/images/@i.Image" alt=""/></div>
                                <div></div>
                            </div>
                        </div>
                        <div class="col-md-7 animate-box">
                            <a asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@i.PostId" class="fh5co_magna py-2"> @i.PostTitle </a>
                            <a href="single.html" class="fh5co_mini_time py-3"> @i.PostCreatoinDate </a>
                            <div class="fh5co_consectetur"> @i.PostDetials
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Terms</div>
                </div>
                <div class="clearfix"></div>
                <div class="fh5co_tags_all">
                    @foreach (var i in Model.indexTerms)
                    {
                        <a  class="fh5co_tagg" asp-controller="UserHome" asp-action="TermIndex" asp-route-TermId="@i.TermId">@i.TermName</a>

                    }
                </div>
            </div>
        </div>
    </div>
</div> 

dgPadCmsUser/Views/UserHome/SinglePost.cshtml
<!DOCTYPE html>
<!--
    24 News by FreeHTML5.co
    Twitter: https://twitter.com/fh5co
    Facebook: https://fb.com/fh5co
    URL: https://freehtml5.co
-->
<html lang="en" class="no-js">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>24 News — Free Website Template, Free HTML5 Template by FreeHTML5.co</title>
    <link href="css/media_query.css" rel="stylesheet" type="text/css" />
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="css/animate.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="css/owl.theme.default.css" rel="stylesheet" type="text/css" />
    <!-- Bootstrap CSS -->
    <link href="css/style_1.css" rel="stylesheet" type="text/css" />
    <!-- Modernizr JS -->
    <script src="js/modernizr-3.5.0.min.js"></script>
</head>
<body class="single">

    <div id="fh5co-title-box"> 
        <img src="/images/@ViewBag.post.Image" height="100%" width="100%">
        <div class="overlay"></div>
        <div class="page-title">
            <span>@ViewBag.post.PostCreatoinDate</span>
            <h2>@ViewBag.post.PostTitle</h2>
        </div>
    </div>
    <div id="fh5co-single-content" class="container-fluid pb-4 pt-4 paddding">
        <div class="container paddding">
            <div class="row mx-0">
                <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                    <p>
                        @ViewBag.post.PostDetials
                    </p>
                   
                    <h3>Summary</h3>
                    <p>
                        @ViewBag.post.PostSummary
                    </p>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                    <div>
                        <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="fh5co_tags_all">
                        @foreach (var i in ViewBag.terms)
                        {
                            <a class="fh5co_tagg" asp-controller="UserHome" asp-action="TermIndex" asp-route-TermId="@i.TermId">@i.TermName</a>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <!--<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    <!-- Waypoints -->
    <script src="js/jquery.waypoints.min.js"></script>
    <!-- Parallax -->
    <script src="js/jquery.stellar.min.js"></script>
    <!-- Main -->
    <script src="js/main.js"></script>
    <script>if (!navigator.userAgent.match(/Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile/i)) { $(window).stellar(); }</script>

</body>
</html>

dgPadCmsUser/Views/UserHome/TaxonomyIndex.cshtml
<div class="container-fluid pt-3">
    <div class="container animate-box" data-animate-effect="fadeIn">
         <div>
                <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">@ViewBag.taxonomy.TaxonomyName</div>
         </div>
        <div class="owl-carousel owl-theme js" id="slider1">
            @foreach (var i in ViewBag.TaxonomyPosts)
            {
                <div class="item px-2">
                    <div class="fh5co_latest_trading_img_position_relative">
                        <div class="fh5co_latest_trading_img">
                            <img src="/images/@i.Image"  alt=""
                             class="fh5co_img_special_relative" />
                        </div>
                        <div class="fh5co_latest_trading_img_position_absolute"></div>
                        <div class="fh5co_latest_trading_img_position_absolute_1">
                            <a asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@i.PostId" class="text-white"> @i.PostTitle </a>
                            <div class="fh5co_latest_trading_date_and_name_color"> @i.PostCreatoinDate</div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

dgPadCmsUser/Views/UserHome/TermIndex.cshtml
<div class="container-fluid pt-3">
    <div class="container animate-box" data-animate-effect="fadeIn">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">@ViewBag.term.TermName</div>
        </div>
        <div class="owl-carousel owl-theme js" id="slider1">
            @foreach (var i in ViewBag.TermPosts)
            {
                if (i.PostTypeId == 6)
                {
                    <div class="item px-2">
                    <div class="fh5co_hover_news_img">
                        <div class="fh5co_hover_news_img_video_tag_position_relative">
                            <div class="fh5co_news_img">
                                <iframe width="100%" height="200" src="@i.VideoUrl" ></iframe>
                            </div>
                            <div class="fh5co_hover_news_img_video_tag_position_absolute_1 fh5co_hide" id="play-video">
                                <div class="fh5co_hover_news_img_video_tag_position_absolute_1_play_button_1">
                                    <div class="fh5co_hover_news_img_video_tag_position_absolute_1_play_button">
                                        <span><i class="fa fa-play"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pt-2">
                            <a asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@i.PostId" class="link-secondary">
                                    <span class="h5">@i.PostTitle </span>
                                </a>
                                <div class="c_g"><i class="fa fa-clock-o"></i>@i.PostCreatoinDate</div>
                        </div>
                    </div>
                </div>
                }
                else
                {
                    <div class="item px-2">
                        <div class="fh5co_latest_trading_img_position_relative">
                            <div class="fh5co_latest_trading_img">
                                <img src="/images/@i.Image" alt=""
                                 class="fh5co_img_special_relative" />
                            </div>
                            <div class="fh5co_latest_trading_img_position_absolute"></div>
                            <div class="fh5co_latest_trading_img_position_absolute_1">
                                <a asp-controller="UserHome" asp-action="SinglePost" asp-route-postId="@i.PostId" class="text-white"> @i.PostTitle </a>
                                <div class="fh5co_latest_trading_date_and_name_color"> @i.PostCreatoinDate</div>
                            </div>
                        </div>
                    </div>
                }

            }
        </div>
    </div>
</div>