dgPadCms/Areas/Admin/Controllers/PostController.cs
using dgPadCms.Infrastructure;
using dgPadCms.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace dgPadCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin,editor")]
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly dgPadCmsContext context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public PostController(dgPadCmsContext context, IWebHostEnvironment webHostEnvironment)
        {
            this.context = context;
            this.webHostEnvironment = webHostEnvironment;

        }
        public  async Task<IActionResult> Index()
        {
            List<Post> posts = await context.Posts.Include(x => x.PostType).ToListAsync();

            return View(posts);
        }

        
        // GET /admin/Post/create
        public async Task<IActionResult> Create(int? postTypeId = null )
        {

            ViewBag.postTypeId = postTypeId;

            if (!postTypeId.HasValue)
            {
                ViewBag.postType = await context.PostTypes.ToListAsync();
                return View();
            }
            else
            {
                ViewBag.PostType = await context.PostTypes.FindAsync(postTypeId);

                var taxonomies = await context.PostTypeTaxonomies.Where(x => x.PostTypeId == postTypeId).ToListAsync();

                List<int> TaxonomiesId = new List<int>();
                
                foreach ( var i in taxonomies)
                {
                    TaxonomiesId.Add(i.TaxanomyId);
                }

                var terms = await context.Terms.Where(x => TaxonomiesId.Contains(x.TaxonomyId)).ToListAsync();

                ViewBag.terms = terms;

                return View();

            }
        }

        //POST /admin/Post/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post, List<int> termIds)
        {
            ViewBag.postTypes = await context.PostTypes.OrderBy(x => x.PostTypeTitle).ToListAsync();
            //ViewBag.postTypeId = post.PostTypeId;
            //ViewBag.PostType = await context.PostTypes.FindAsync(post.PostTypeId);
            post.PostCreatoinDate = DateTime.Now;
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create",new { postTypeId = post.PostTypeId } );
            }
            if (termIds == null || termIds.Count == 0)
            {
                ModelState.AddModelError("", "At least one term must be chosen!");
                return RedirectToAction("Create", new { postTypeId = post.PostTypeId });
            }
            context.Add(post);
            await context.SaveChangesAsync();

            string imageName = "noimage.png";
            if (post.ImageUpload != null)
            {
                string uploadsDir = Path.Combine(webHostEnvironment.WebRootPath, "media/images");
                imageName = Guid.NewGuid().ToString() + " " + post.ImageUpload.FileName;
                string filePath = Path.Combine(uploadsDir, imageName);
                FileStream fs = new FileStream(filePath, FileMode.Create);
                await post.ImageUpload.CopyToAsync(fs);
                fs.Close();
                post.Image = imageName;
            }

            foreach (var i in termIds)
            {
                PostTerm postTerm = new PostTerm()
                {
                    PostId = post.PostId,
                    TermId = i

                };
                context.Add(postTerm);
            }
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET /admin/post/edit/id

        public async Task<IActionResult> Edit(int PostId)
        {
            var post = await context.Posts.FindAsync(PostId);
            ViewBag.postType = await context.PostTypes.FindAsync(post.PostTypeId);

            var taxonomies = await context.PostTypeTaxonomies.Where(x => x.PostTypeId == post.PostTypeId).ToListAsync();

            List<int> TaxonomiesId = new List<int>();

            foreach (var i in taxonomies)
            {
                TaxonomiesId.Add(i.TaxanomyId);
            }

            var terms = await context.Terms.Where(x => TaxonomiesId.Contains(x.TaxonomyId)).ToListAsync();

            ViewBag.terms = terms;

            return View(post);
        }

        // post /admin/post/edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post post, List<int> termIds)
        {
            if (!ModelState.IsValid)
                return View(post);

            if (termIds.Count() == 0)
            {
                ModelState.AddModelError("", "The taxonomy list is empty");
                return View(post);
            }

            if (post.ImageUpload != null)
            {
            
                string uploadsDir = Path.Combine(webHostEnvironment.WebRootPath, "media/images");

                if (!string.Equals(post.Image, "noimage.png"))
                {
                    string oldImagePath = Path.Combine(uploadsDir, post.Image);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                string imageName = Guid.NewGuid().ToString() + " " + post.ImageUpload.FileName;
                string filePath = Path.Combine(uploadsDir, imageName);
                FileStream fs = new FileStream(filePath, FileMode.Create);
                await post.ImageUpload.CopyToAsync(fs);
                fs.Close();
                post.Image = imageName;
            }

            context.Update(post);
            await context.SaveChangesAsync();

            List<PostTerm> postTerms = await context.PostTerms.Where(x => x.PostId == post.PostId).ToListAsync();

            foreach (var x in postTerms)
            {
                context.PostTerms.Remove(x);
            }

            await context.SaveChangesAsync();

            foreach (var i in termIds)
            {
                PostTerm postTerm = new PostTerm()
                {
                    PostId = post.PostId,
                    TermId = i

                };
                context.Add(postTerm);
            }
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int PostId)
        {
            Post post = await context.Posts.FindAsync(PostId);
            context.Remove(post);
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

dgPadCms/Areas/Admin/Controllers/RolesController.cs
using dgPadCms.Infrastructure;
using dgPadCms.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace dgPadCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AppUser> userManager;
        private readonly dgPadCmsContext context;


        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager, dgPadCmsContext context)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.context = context;
        }

        // GET /admin/roles
        public IActionResult Index() => View(roleManager.Roles);

        // GET /admin/roles/create
        public IActionResult Create() => View();

        // POST /admin/roles/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([MinLength(2), Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    TempData["Success"] = "The role has been created!";
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors) ModelState.AddModelError("", error.Description);
                }
            }

            ModelState.AddModelError("", "Minimum length is 2");
            return View();
        }

        // GET /admin/roles/edit/5
        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);

            List<AppUser> members = new List<AppUser>();
            List<AppUser> nonMembers = new List<AppUser>();

            foreach (AppUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }

            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        // POST /admin/roles/edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleEdit roleEdit)
        {
            IdentityResult result;

            foreach (string userId in roleEdit.AddIds ?? new string[] { })
            {
                AppUser user = await userManager.FindByIdAsync(userId);
                result = await userManager.AddToRoleAsync(user, roleEdit.RoleName);
            }

            foreach (string userId in roleEdit.DeleteIds ?? new string[] { })
            {
                AppUser user = await userManager.FindByIdAsync(userId);
                result = await userManager.RemoveFromRoleAsync(user, roleEdit.RoleName);
            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        // GET /admin/roles/delete/id
        public async Task<IActionResult> Delete(string roleId)
        {
            var role = await context.Roles.Where(x => x.Id == roleId).FirstOrDefaultAsync();      
            context.Roles.Remove(role);
            context.SaveChanges();

            
            return RedirectToAction("Index");
        }
    }
}

dgPadCms/Areas/Admin/Controllers/TermController.cs
using dgPadCms.Infrastructure;
using dgPadCms.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace dgPadCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin,editor")]
    [Area("Admin")]

    public class TermController : Controller

    {
        private readonly dgPadCmsContext context;

        public TermController(dgPadCmsContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Term> terms = await context.Terms.Include(x => x.Taxonomy).ToListAsync();
            
            return View(terms);

        }

        // GET /admin/term/create
        public IActionResult Create()
        {
            ViewBag.taxonomies = new SelectList(context.Taxonomies.OrderBy(x => x.TaxonomyName), "TaxonomyId", "TaxonomyName");

           return View();
        }
        // POST /admin/term/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Term term)
        {
            ViewBag.taxonomies = new SelectList(context.Taxonomies.OrderBy(x => x.TaxonomyName), "TaxonomyId", "TaxonomyName");

            var termCheck = await context.Terms.FirstOrDefaultAsync(x => x.TermName == term.TermName);
            if (termCheck != null)
                ModelState.AddModelError("", "The term already exists.");

            if (ModelState.IsValid)
            {

                context.Add(term);
                await context.SaveChangesAsync();

                TempData["Success"] = "The term has been added!";

                return RedirectToAction("Index");
            }

            return View(term);
        }

        // GET /admin/term/edit/id

        public async Task<IActionResult> Edit(int Termid)
        {
            Term term = await context.Terms.FindAsync(Termid);
            ViewBag.taxonomies = new SelectList(context.Taxonomies.OrderBy(x => x.TaxonomyName), "TaxonomyId", "TaxonomyName", term.Taxonomy);

            if (term == null)
            {
                return NotFound();
            }

            return View(term);
        }

        // POST /admin/term/edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( Term term)
        {
            ViewBag.taxonomies = new SelectList(context.Taxonomies.OrderBy(x => x.TaxonomyName), "TaxonomyId", "TaxonomyName");

            if (ModelState.IsValid)
            {
                var termCheck = await context.Terms.FirstOrDefaultAsync(x => x.TermName == term.TermName);
                if (termCheck != null)
                {
                    ModelState.AddModelError("", "The term already exists.");
                    return View(term);
                }

                context.Update(term);
                await context.SaveChangesAsync();

                TempData["Success"] = "The term has been edited!";

                return RedirectToAction("Index");
            }

            return View(term);
        }

        // GET /admin/term/delete/id
        public async Task<IActionResult> Delete(int TermId)
        {
            Term term = await context.Terms.FindAsync(TermId);

            if (term == null)
            {
                TempData["Error"] = "The term does not exist!";
            }
            else
            {
                context.Terms.Remove(term);
                await context.SaveChangesAsync();

                TempData["Success"] = "The term has been deleted!";
            }

            return RedirectToAction("Index");
        }
    }
}

dgPadCms/Areas/Admin/Controllers/UsersController.cs
using dgPadCms.Infrastructure;
using dgPadCms.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace dgPadCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly dgPadCmsContext context;

        public UsersController(UserManager<AppUser> userManager, dgPadCmsContext context)
        {
            this.userManager = userManager;
            this.context = context;
        }

        public IActionResult Index()
        {
            return View(userManager.Users);
        }

        public IActionResult Delete(string userId)
        {
            var user = context.Users.Find(userId);
            if (user == null) return NotFound();
            context.Users.Remove(user);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

dgPadCms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dgPadCms</title>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/21/21601.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <ul class="navbar-nav flex-grow-1">
                    @if (User.IsInRole("admin"))
                    {
                        <a class="navbar-brand" asp-area="Admin" asp-controller="Post" asp-action="Index">dgPadCms</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Users" asp-action="Index" class="nav-link text-dark">Users</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Roles" asp-action="Index" class="nav-link text-dark">Roles</a>
                        </li>
                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Taxonomy" asp-action="Index" class="nav-link text-dark">Taxonomy</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Term" asp-action="Index" class="nav-link text-dark">Term</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="PostType" asp-action="Index" class="nav-link text-dark">PostType</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Post" asp-action="Index" class="nav-link text-dark">Post</a>
                        </li>
                    }
                    @if (User.IsInRole("editor")  )
                    {
                        <a class="navbar-brand" asp-area="Admin" asp-controller="Post" asp-action="Index">dgPadCms</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Taxonomy" asp-action="Index" class="nav-link text-dark">Taxonomy</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Term" asp-action="Index" class="nav-link text-dark">Term</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="PostType" asp-action="Index" class="nav-link text-dark">PostType</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-area="Admin" asp-controller="Post" asp-action="Index" class="nav-link text-dark">Post</a>
                        </li>
                    }
                    <li class="nav-item ml-1">
                        <a href="https://localhost:5003/" target="_blank" class="nav-link text-dark">User Website</a>
                    </li>
                </ul>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    
                    <ul class="navbar-nav flex-grow-1 justify-content-end">

                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Edit" class="btn btn-primary">My Account</a>
                        </li>

                        <li class="nav-item ml-1">
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Hi, @User.Identity.Name, Log out</a>
                        </li>
                    }
                    else{
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="btn btn-success">Log in</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
                            </li>
                    }
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            <div class="col">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - dgPadCms>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

dgPadCms/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}